### ISSUE TITLE
Sliding Sync / Sync v4 Tracking Issue

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#1014]
Temporary measures:
 - [ ] allow sliding-sync to be optional feature on FFI

Missing features:
 - [ ] Extensions, see also https://github.com/ruma/ruma/pull/1273
    - [ ] `ToDevice`-Messages
    - [ ] E2ee Support
    - [ ] Account Data
 - [ ] Notifications support 
 - [ ] Sync v2/v3 fallback support
