### ISSUE TITLE
Sliding Sync Stabilization tracking

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#1359]
This is an overview issue regarding stabilization of sliding sync as a non-experimental default-on feature towards the 1.0 release of the sliding sync proxy.

We have to
 - [x] #1377
 - [x] API docs for the crate and all its types, #1467
 - [x] check robust-ness of session restart, in particular regarding extensions and their current state, refs #1418
 - [x] timeline trickle supoort
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1475
 - [x] https://github.com/matrix-org/matrix-rust-sdk/issues/1474
 - [x] https://github.com/matrix-org/matrix-rust-sdk/issues/1476

Done:

 - [x] subsribeAndAddListener helper for FFI,  #1361
 - [x] GrowingFullSync skips a beat upon internal restart some times, fixed in #1372 refs https://github.com/vector-im/element-x-ios/issues/461
 - [x] separate unfreezing of views, fixed in #1372
 - [x] gaps in timelines if the room ran out of view, fixed in #1372
 -  [x] we might be dropping server responses with the spawn-cancel, thus leaving to us missing messages, fixed in #1372
 - [x] update to latest JSON format https://github.com/matrix-org/matrix-rust-sdk/pull/1399 
    - [x] there is already some updates in fields which we don't have in the types yet
    - [x] but there will be more to come with 1.0: named views & per-view-extensions
 - [x] over the window-edge index changes, #1418
 -  ~~fully transparent fallback to v2 if v3 is unavailable~~

**Comment by Hywan** [comment]
Replaced by https://github.com/matrix-org/matrix-rust-sdk/issues/1579.
