### ISSUE TITLE
[meta] feat(sdk): Making Sliding Sync Great

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#1579]
This is a meta issue listing things I would like to do on Sliding Sync to make it clean, testable, and stable:

## Clean Up

A “clean up” is more than just cleaning the code. We are reviewing line by line, and improving everything we see.

- [x] Split the giant Rust module into smaller modules, #1535
- [x] Clean up `builder`
  - [x] #1535
  - [x] #1541
- [x] Clean up `client`
- [ ] Clean up `mod`/`sliding_sync`
  - [x] #1520
  - [x] #1538
  - [x] #1537
  - [x] #1582
  - [ ] #1632
- [x] Clean up `room`
  - [x] #1529
  - [x] #1559
- [x] Clean up `list`
  - [x] #1540 
  - [x] #1598
- [x] Clean up or rewrite the FFI bindings
  - [x] #1536
  - [x] #1556
  - [x] #1602
  - [x] #1631

## Stable Performances

- [x] Reduce memory usage: this is hard to measure but basically we want to remove as much `clone` as possible, the old version was containing too much of it.
  - [x] #1567
- [x] Reduce inner locks, and use more meaningful locks: the problem is that all the inner locks create rac conditions, we must update the code to use more meaningful locks
  - [x]  #1601
- [x] Make the code more robust, protecting inner states etc.
  - [x] #1440
  - [x] #1454 
  - [x] #1557
- [ ] Reduce the API surface: “coercing” particular workflows.

## Features/Bug fixes

- [x] Map responses to request: a “request stream” must have its own unique `txn_id`, so that we can verify the received responses map to a specific request; it will help to support concurrent request (which is breaking the spec, but happens in reality)
  - [x] https://github.com/ruma/ruma/pull/1502
  - [x] #1595
- [x] Fix the `pos` value not being incremented correctly
  - [x] #1601
  - [x] Needs to be confirmed that the PR above fixes multiple sync/states bugs.
- [x] Handle stream cancellation directly inside the Rust SDK instead of inside the FFI bindings
  - [x] #1601
- [x] Resolve duplicates in the timeline queue, #1478
- [x] Allow to receive partial responses from the server:
  - [x] #1596
  - [x] #1638
- [ ] Bot mode: make SS usable for bots
  - [ ] #1475
- [ ] Bridge mode: make SS usable for bridges
