### ISSUE TITLE
[meta] feat(sdk): Making Sliding Sync Tested

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#1670]
Sequel of https://github.com/matrix-org/matrix-rust-sdk/issues/1579.

![output2](https://user-images.githubusercontent.com/946104/225581283-2e9b1ad8-81b9-4ff3-8452-302f14ce77c3.jpg)

<p align="center"><small>Image generated with <a href="https://deepai.org/machine-learning-model/text2img">DeepAI</a></small></p>

Now the code has been cleaned up and that major bugs have been fixed, we can focus on testing the code. So far, there is a small integration test suites, but we want me.

# Unit test suites

Ideally, we need multiple specific, tailored macros to simplify contributions from the outside, something close to a DSL. I'll do my best.

Here we are types that must be have a unit test suite:

- [x] `SlidingSync`
  - [x] #1757
  - [x] #1758
- [x] `SlidingSyncList`
  - [x] #1672
  - [x] #1681
  - [x] #1695
  - [x] #1694
  - [x] #1699
  - [x] #1696
  - [x] #1754
  - [x] Undo hacks to solve https://github.com/matrix-org/sliding-sync/issues/52
    - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/1833
- [x] `SlidingSyncListRequestGenerator`
  - [x] #1667
- [x] `SlidingSyncRoom`
  - [x] #1861
- [x] Cache
  - [x] #1736

Bugs opened on Sliding Sync Proxy:

- [x] https://github.com/matrix-org/sliding-sync/issues/52

# Integration test suites

To be defined. There is many ways to approach this. Either by using some randomization, or using temporal-logic based testing, or using contract-based testing with various contract-coverage-based test generation. I want to do something super clean.

I also want to provide a simple DSL to write the test cases easily, without having the care about the Rust implementation.

I need to think about it for a moment.

* [x] https://github.com/matrix-org/matrix-rust-sdk/pull/1921
