### ISSUE TITLE
[Media+Timeline] Local echo support for media attachments

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1732]
Sending media attachments through the Timeline should make use of local echoes for a seamless experience.

---

## Sub project: handle media upload in the send queue

- ~~break apart uploading in a small state machine that can be reused in the send queue~~
  - Turns out this was not strictly required, because the code in the send queue and out are so different.
- [x] modify the send queue storage format so it takes care of "requests", not only sending "event content"
- [x] add a new request type for uploading a media
- [x] (draw the rest of the freaking howl)
- [x] handle medias local echoes in the timeline

## Tasks

- https://github.com/matrix-org/matrix-rust-sdk/pull/4140
- https://github.com/matrix-org/matrix-rust-sdk/pull/4149 (cache media and thumbnail)

## Related

- https://github.com/matrix-org/matrix-rust-sdk/issues/1968
- [element-meta task](https://github.com/element-hq/element-meta/issues/2549)

**Comment by jplatte** [comment]
Synapse implements asyncronous uploads from [v1.97.0](https://github.com/matrix-org/synapse/releases/tag/v1.97.0) onwards, with which this should be easier to implement (can generate a transaction ID / get an event ID for it in parallel with the upload). Ruma also supports [the new endpoint](https://docs.rs/ruma/latest/ruma/api/client/media/create_content_async/index.html).
