### ISSUE TITLE
[meta] `EventCache` storage

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#3280]
![output](https://github.com/matrix-org/matrix-rust-sdk/assets/946104/d98fedf7-5c3b-4e5c-b21b-0a2278cbb09b)

---

`matrix_sdk::EventCache` is a new module that has been introduced with #3058. The idea is to manage all events inside the Rust SDK in a single place. An important user of `EventCache` is the `matrix_sdk_ui::Timeline`.

`EventCache` uses a new data structure to organize all events, `LinkedChunk`, since:

* #3166
* #3230

This issue describes the plan to get a persistent storage for `EventCache`, along with the ability to make it reactive.

# Persistent storage

In order to create a persistent storage for `EventCache`, we need a mechanism that listens to `LinkedChunk` updates, and map these updates to database operations (like `INSERT`, `DELETE` and so on).

We initially went to using a reactive mechanism (like `ObservableLinkedChunk`), but like any reactive mechanisms, we need to handle the _lag_.

> [!NOTE]
> What is a lag? When new updates are generated, they are usually accumulated in a buffer. This buffer is drained by subscribers of the observed value. When the buffer is full, which can happen because subscribers _lag_ to consume updates, the buffer is reset.

The lag, in this case, is pretty problematic. In case of a lag, the database will be out of sync —data will be missing—, and there is no easy way to get them again. In case of a lag, we might imagine to reset the database and to rewrite everything again, but not all events are loaded in memory. Alternatively, we may want to recompute all the differences between what is in memory and what is inside the database, but again, it's not an easy problem. Anyway, it implies more guards and more complexity.

Instead, we've decided to define a `LinkedChunkListener` trait, used by `LinkedChunk`, onto which methods will be called on some particular operations, like `insert_chunk`, `remove_chunk`, `insert_events` and `remove_events`, that's probably all we need.

The cons:

* It's a new API to manage,
* It cannot be re-used by something else. It exists for one usage only.

The pros:

* It's _immediate_: it removes the problem of the lag introduced by the initial reactive approach,
* It's easily unit-testable!
* The API is quite small and clearly not complex at all, it's straighforward.

## Tasks

* [x] Create `LinkedChunkListener`: https://github.com/matrix-org/matrix-rust-sdk/pull/3281
* [x] Create a persistent storage for `EventCache`; write mode: from memory to persistent storage:
  * [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4192
  * [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4285
  * [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4299
  * [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4298
  * [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4340
* [x] Create a `LinkedChunk` from the storage; read mode: from persistent storage to memory:
  * [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4318
* [x] **Disable** the persistent storage for `EventCache`.

# Reactive `EventCache`

Right now, there is no satisfying way to get a stream of `EventCache` updates. The only mechanism that exists so far is `RoomEventCache::subscribe`. It returns a `tokio::sync::mpsc::Receiver<RoomEventCacheUpdate>`. `RoomEventCacheUpdate` is defined like so:

https://github.com/matrix-org/matrix-rust-sdk/blob/ac0bc95c253c5d46fec31378016497f433e0067d/crates/matrix-sdk/src/event_cache/mod.rs#L816-L838

## Constraint: Prepare for reconciliation

This is OK-ish for the moment (at the time of writing), but it will quickly show limitations, in particular with the reconciliation.

> [!NOTE]
>  When events are received in different orders —e.g. between `/messages`, `/context` or `/sync`—, it's important to re-order them. We call that _reconciliation_. It's far, far, faaar from trivial. Actually, there is no solution to this problem, but we will try to make the best heuristics as possible.

Why reconciliation is going to create a problem here? Because it's impossible to represent an update like: “remove item at position $p$, and insert item at position $q$”. The only possible updates so far are “clear” and “append”.

The assiduous reader (oh, hi[^1]) will think: “How does it work with back- or front-pagination?”. Thanks for asking. Let's make a detour.

## Constraint: Pagination

Frontpagination isn't implemented yet (not something hard, just not here yet). Backpagination is done with `RoomEventCache::backpaginate`. It returns a `BackPaginationOutcome`, defined like so:

https://github.com/matrix-org/matrix-rust-sdk/blob/ac0bc95c253c5d46fec31378016497f433e0067d/crates/matrix-sdk/src/event_cache/mod.rs#L792-L814

Ah. Isn't it using `RoomEventCacheUpdate`? Well, no, because of the `Timeline`! The API from `EventCache` has been extracted from the `Timeline`. The `Timeline` had and still has 2 sources of updates: `/sync` and `/messages` for pagination.

Would it be hard to switch to a single `Stream<Item = SyncTimelineEvent>`? Well. Yes and no.

* For `/sync`, the `Timeline` listens to `RoomEventCache::subscribe`:

https://github.com/matrix-org/matrix-rust-sdk/blob/ac0bc95c253c5d46fec31378016497f433e0067d/crates/matrix-sdk-ui/src/timeline/builder.rs#L133-L137

* For `/messages`, the `Timeline` has a dedicated mechanism that calls `/messages` in a loop until $n$ `TimelineItem`s are received. This is different of $n$ `SyncTimelineItem`, because some events are state events and cannot be displayed to the user:

https://github.com/matrix-org/matrix-rust-sdk/blob/ac0bc95c253c5d46fec31378016497f433e0067d/crates/matrix-sdk-ui/src/timeline/pagination.rs#L49-L51

What do we want? A single source of data for `Timeline`.
What does it require? Change the backpagination mechanism. Not a _big deal_, it's doable. The biggest difficulty is that the `Timeline` will ask for data that will be injected to another place (`Timeline::paginate_backwards` will see the results of `RoomEventCache::backpaginate` via `RoomEventCache::subscribe`). It's not easy to connect both.
How to do it? Glad you ask.

## The solution: Step 1

`LinkedChunk` must expose a `Stream<Item = Vec<VectorDiff<SyncTimelineEvent>>>`-like API, something like:

```rust
impl LinkedChunk {
    fn subscribe_as_vector(&self) -> (Vec<SyncTimelineEvent>, impl Stream<Item = Vec<VectorDiff<SyncTimelineEvent>>>) {
        todo!()
    }
```

Easy right? Well. No. `LinkedChunk` _is not_ a `Vector`. The algorithm is going to be fun here. `LinkedChunk::subscribe_as_vector` **should fake it's a `Vector` and should emit `VectorDiff`**, _à la_ [`eyeball_im::ObservableVector`](https://docs.rs/eyeball-im/latest/eyeball_im/struct.ObservableVector.html).

Of course, `RoomEventCache::subscribe` must be rewritten to use `LinkedChunk::subscribe_as_vector`.

## The solution: Step 2

`Timeline` must listen to `RoomEventCache::subscribe` but for _all updates_. Then, `Timeline` will map `Stream<Item = Vec<VectorDiff<SyncTimelineItem>>>` into `TimelineItem`s that will be inserted/deleted/moved in the correct places inside its own `ObservableVector<TimelineItem>` inside `TimelineInnerState`:

https://github.com/matrix-org/matrix-rust-sdk/blob/ac0bc95c253c5d46fec31378016497f433e0067d/crates/matrix-sdk-ui/src/timeline/inner/state.rs#L71-L75

This is going to be delicate.

## Tasks

The 2 following lists can be done in parallel:

Tasks on `EventCache`:

- [x] Create `LinkedChunk::subscribe_as_vector`:
   - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3384
   - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3392

Tasks on `EventCache` and `Timeline`:

- [x] Improve/refactor the pagination mechanism of `Timeline` to `EventCache` so that `EventCache` is the only place to have pagination logics. `Timeline` must entirely depend on `EventCache`.

The following list must be done after the 2 previous lists:

- [x] Update `RoomEventCache::subscribe` to use `LinkedChunk::subscribe_as_vector`:
  - What must actually be done is: we update `RoomEventCacheUpdate` to include the `VectorDiff`, and the `Timeline` must handle these `VectorDiff` itself (there is already a `TimelineItemPosition` type, it must be expanded a little bit)
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3471
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3472
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4317
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4321
- [x] Update `Timeline` to handle a `Stream<Item = Vec<VectorDiff<SyncTimelineItem>>>`.
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3512
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3525
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3526
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3527
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3550
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4328
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4330
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4331
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4370
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4377
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4408

# Lazy `EventCache`: Combine pagination and persistent storage

Before being able to enable persistent storage in `EventCache`, one last problem must be addressed.

`RoomEventCache` will use `RoomEvents` (which uses `LinkedChunk`) to load events from the persistent storage. That's fine. However, we don't want to load _all events_ from the persistent storage. Imagine rooms with 1'000'000 events: do we want to load all the events in memory? Absolutely no! `RoomEventCache` must be lazy: it must load only the $n$ newest chunks from the persistent storage.

OK, but what happens when we backpaginate?

* We must load events from the persistent storage first,
* We must run a proper backpagination (with `/messages`) to see if events aren't missing from the federation that could have missed by `/sync`,
* We must reconciliate both.

> [!NOTE]
> A more detailed plan is being drafted by @bnjbvr and @Hywan to define when running a network request (`/messages`) is necessary or not necessary. The heuristic is not trivial, all edge-cases must be well-defined and considered carefully.

Once we have this mechanism in-place, we can enable the persistent storage for `EventCache`.

## Tasks

* [x] `RoomEventCache` is lazy: load chunks on-demand,
* [x] `RoomEventCache` is able to backpaginate from its persistent storage and from `/messages` at the same time,
* [x] Finally, enable the persistent storage for `EventCache` 🎉.

# Naive reconciliation

To start with, we can implement a super native reconciliation algorithm that will simply remove duplicated events. For a first shot, it's totally fine. A better reconciliation algorithm can be defined later. For the record, what is present now is the _remove duplicated events_ approach.

What we want to ensure is that the reconciliation algorithm will modify events in `LinkedChunk`, which will propagate to the persistent storage via `LinkedChunkListener` and to the `Timeline` via `RoomEventCache::subscribe`. That's one of the main goal of this proposed designed.

## Tasks

* [x] https://github.com/matrix-org/matrix-rust-sdk/pull/4174

# Conclusion

This plan provides a solution to support a reconciliation mechanism in a single place. It will benefit to other users, like `Timeline`. The `Timeline` needs to be refactored due to having 2 source of updates, one for `/sync` (live events), and one for `/messages` (front- and back-paginations of old events).

Because `EventCache` will be reactive, it will simplify a lot all the testing aspects:
* `EventCache` will be easy to test: assert a stream,
* `Timeline` will be super easy to test without having to mock a server will all its possible requests: simply generate a stream that will emit what we want to test exactly, it's a matter of writing the following code for the _inputs_ of the `Timeline`:

```rust
let inputs = stream! {
    yield vec![VectorDiff::Append { values: events![…, …, …] }];
    yield vec![VectorDiff::Remove { index: … }];
    yield vec![VectorDiff::Insert { index: …, value: … }];
};
```

* Components will be fully decoupled. Each part will be unit-tested. It will increase the robustness of the `Timeline`.

# Bonus

* `LinkedChunk` uses mutation-based testing and property-based testing:
  - [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3460 
- [x] https://github.com/matrix-org/matrix-rust-sdk/pull/3578

---

* Address #3058
* Address https://github.com/element-hq/element-meta/issues/2405

[^1]: Mark?

**Comment by Hywan** [comment]
Task distribution. First level items must be executed in that order. Other level items of the same level can be done in parallel.

* [ ] `EventCacheStore`
  * [ ] Add `EventCacheStore::handle_linked_chunk_update` with empty implementations for `MemoryStore` and SQLite.
  * [ ] Implement `EventCacheStore::handle_linked_chunk_update` for `MemoryStore`
    * [ ] Implement `RelationalLinkedChunk`
  * [ ] Implement `EventCacheStore::handle_linked_chunk_update` for SQLite.
* [ ] `EventCache`
  * [ ] Load from store
    * [ ] Lazy-load events
      * [ ] Being able to build a `LinkedChunk` chunk-by-chunk manually
  * [ ] Sync
    * [ ] Store events
  * [ ] Pagination
    * [ ] Load from the store
    * [ ] Load from the network
    * [ ] Store events from network
  * [ ] Remove `AllEvents`
    * [ ] Update the `MemoryStore` and SQLite representation to include a `relates_to` column to create 1:N relations between events
    * [ ] Repalce `AllEvents`
* [ ] Clean up
  * [ ] Sliding Sync
    * [ ] Kill `timeline_queue`

**Comment by Hywan** [comment]
Most of the point has been addressed. The project has now been activated in a major client (Element X). Time to close this issue. I'm opening new issues for the remaining tasks.

**Comment by Hywan** [comment]
Remaining tasks:

- https://github.com/matrix-org/matrix-rust-sdk/issues/4874
- https://github.com/matrix-org/matrix-rust-sdk/pull/4308
- https://github.com/matrix-org/matrix-rust-sdk/issues/3079
- https://github.com/matrix-org/matrix-rust-sdk/issues/3886
