### ISSUE TITLE
WASM tracking

### ISSUE THREAD

**Issue by stoically** [matrix-org/matrix-rust-sdk#35]
- [x] EventEmitter and CryptoStore: Probably requires an alternative trait without `Send + Sync` (https://github.com/matrix-org/matrix-rust-sdk/pull/60)
- [x] Sleeping panics: Possibly [wasm-timer](https://github.com/tomaka/wasm-timer) could help fix that. Also `Instant` is using the instant crate but `wasm-timer` provides an `Instant` as well, so could get potentially changed
- [x] Switch to crates.io version of `futures-locks` once a new version gets published (~~https://github.com/asomers/futures-locks/issues/38~~) (#94)
- [x] Open PRs to allow olm to compile
  - [x] libolm make target
  - [x] https://github.com/engineerd/cjson/pull/1
  - [x] [BrainBlasted/olm-sys#8](https://gitlab.gnome.org/BrainBlasted/olm-sys/-/merge_requests/8)
- [x] CryptoStore needs an IndexedDB Implementation to work reliably (prototype: [indexeddb-cryptostore](https://github.com/poljar/indexeddb-cryptostore)) (https://github.com/matrix-org/matrix-rust-sdk/pull/414)

Extracted from: https://github.com/matrix-org/matrix-rust-sdk/pull/31#pullrequestreview-410036306

**Comment by stoically** [comment]
A possible workaround for the Send+Sync issue could be a proc macro attribute like

`#[cfg_attr(not(target_arch), send_sync)]`

which adds the bound for non-wasm targets.

**Comment by MTRNord** [comment]
And a specific macro for async_trait on EventEmitter as the send_sync macro doesn't work:

```rust
/// A wasm32 compatible wrapper for the async_trait::async_trait macro
#[proc_macro_attribute]
pub fn async_trait(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let attrs = r#"
        #[cfg_attr(target_arch = "wasm32", async_trait::async_trait(?Send))]
        #[cfg_attr(not(target_arch = "wasm32"), async_trait::async_trait)]
    "#;

    let mut out: TokenStream = attrs.parse().unwrap();
    out.extend(item);
    out
}
```

it replaces `#[async_trait::async_trait]` and `Send + Sync` can get removed

**Comment by MTRNord** [comment]
Also the async_trait macro needs to be used on all impl. You might use `async_trait::async_trait` in non wasm targets directly and can also use on things that only compile to wasm32 `async_trait::async_trait(?Send)`. Just the main definition of EventEmitter needs to use this macro (or the attribures)

**Comment by poljar** [comment]
I forgot to mention this over here, but we have a prototype `CryptoStore` that uses indexeddb over [here](https://github.com/poljar/indexeddb-cryptostore).

It uses a fork of [indexeddb-rs](https://github.com/derekdreery/indexeddb-rs/) since the upstream one doesn't compile, fork is over [here](https://github.com/poljar/indexeddb-rs).

**Comment by stoically** [comment]
Closing as all boxes are checked. Thanks @gnunicorn for the missing piece.
