### ISSUE TITLE
[meta] SSS & PPS

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#3647]
_Here be dragons._

(that's a draft)

This is a meta issue to track the work about _Simplified Sliding Sync_ (SSS) and _Pragmatic Pragmatic Sync_ (PPS)

# Simplified Sliding Sync

Synapse is implementing Sliding Sync natively. Since [the Proxy implementation](https://github.com/matrix-org/sliding-sync) was experimental and was exposing too many features we now know we don't need, we call this project Simplified Sliding Sync.

## Tasks

- [x] Replace the sync `ops` by client-side sorting
- [ ] To Be Defined

# Pragmatic Pragmatic Sync

Pragmatic Pragmatic Sync is another effort to extract some features of Sliding Sync into their own HTTP endpoints.

## Tasks

- [ ] Replace Sliding Sync by `/sync/e2ee`
- [ ] Replace Sliding Sync by the improved `/context`

# Release and Clean Up

Now it's time to clean up the old `matrix_sdk::sliding_sync` implementation.

## Tasks

- [ ] Remove old features of Sliding Sync
- [ ] Remove potential intermediate feature flags
- [ ] Remove the `experimental-sliding-sync` feature flag
