### ISSUE TITLE
MSC3489 Live Location Sharing

### ISSUE THREAD

**Issue by torrybr** [matrix-org/matrix-rust-sdk#3945]
This issue tracks the progress and outstanding work for implementing the functionality described in [MSC3489](https://github.com/matrix-org/matrix-spec-proposals/pull/3489). It involves sending, stopping, and handling `beacon` and `beacon_info` events within the SDK and builds on [events types in Ruma](https://github.com/ruma/ruma/pull/1722/files).

#### Related Communication
Initial discussion can be found in this [draft PR](https://github.com/matrix-org/matrix-rust-sdk/pull/3621).

### Completed Tasks:
- [x] Support for sending, stopping & updating `beacon_info` events in `matrix-sdk` & `matrix-sdk-base`: [PR #3741](https://github.com/matrix-org/matrix-rust-sdk/pull/3741)
- [x] Support for sending `beacon` events in the `matrix-sdk` crate: [PR #3771](https://github.com/matrix-org/matrix-rust-sdk/pull/3771/files)
- [x] Refactor `beacon_info` tests so they are in their own folder: [PR #3794](https://github.com/matrix-org/matrix-rust-sdk/pull/3794)

### In progress:
- [ ] Process incoming `beacon` events and associate them with their referenced `beacon_info`

### Remaining Tasks:
- [ ] Handle cases where `beacon` events arrive before their associated `beacon_info` events
- [ ] Provide a stream for the client to listen to new live location shares
- [ ] Add support for the timeline
- [ ] Add support for FFI bindings

### Questions 
1. I’m currently working on the logic for processing incoming `beacon` events and associating them with their referenced `beacon_info`. Where should this logic be implemented? I assume it will require a lookup for the existing beacon_info in [BaseRoomInfo](https://github.com/matrix-org/matrix-rust-sdk/blob/14ee78c54de1dbe5609f2620fcf398620bd1a91c/crates/matrix-sdk-base/src/rooms/mod.rs#L88).

### Additional Context
The following ideas were suggested by @bnjbvr and should be integrated into the tasks above to improve the ergonomics of working with beacons:

- Provide a stream to listen to new live location shares (client-wide).
- For each live location share, offer a stream to listen to new beacon events and receive updates about the beacon_info itself (e.g., stopped, redacted, etc.).

**Comment by torrybr** [comment]
Thanks for your detailed response regarding the JoinHandle and stream for handling beacon events! I haven't worked much with `JoinHandle` before, so I'm trying to wrap my head around how to integrate it into the event handling logic.

I was looking at [this example in pinned_events_loader.rs](https://github.com/matrix-org/matrix-rust-sdk/blob/4b970e879f3f9cdb0ded2b01b4b00a1692c66f3a/crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs#L142) for guidance on using the event cache, but I'm still unsure how to combine this with your suggestion for processing events with a `JoinHandle`. Would you be able to provide an example or point me to another part of the codebase that demonstrates this kind of pattern?

Seeing how it's been used elsewhere would help me better understand the mechanics.

**Comment by torrybr** [comment]
Posting this snippet from [`Matrix Rust SDK Development`](https://matrix.to/#/!qSsPTKDfMGYqhgiLPJ:flipdot.org/$baTO49eLm_afpDOeseASStE3QMYg-8WleV7_IwREPQc?via=matrix.org&via=element.io&via=acter.global) chatroom which had some talk about this issue:

	•	not the timeline, because it should restrict itself to being a view
	•	not the event cache, to not explode its responsibilites
	•	so could be either a new API object (think: like the send queue), or a method on the room that returns a task (for listening to the "pin violations", whatev that means) and a stream (…or the aforementioned API object)

**Comment by torrybr** [comment]
Here’s my first pass at this, and I think it’s on the right track. I’m running into a couple of issues using `self` inside the JoinHandle, specifically with `self.add_event_handler`, which is is due to my inexperience with using tasks.

```
pub async fn subscribe_to_live_location_shares(
    &self,
) -> (JoinHandle<()>, broadcast::Receiver<LiveLocationShare>) {
    let (sender, receiver) = broadcast::channel(16);

    let handle: JoinHandle<()> = tokio::spawn(async move {
        // TODO implement event cache in the future
        
        let beacon_event_handler_handle = self.add_event_handler({
            move |event: OriginalSyncBeaconEvent| async move {
                // Check if the beacon event has a corresponding beacon info event.
                if let Ok(beacon_info) = self.get_user_beacon_info(event.sender.as_ref()).await {
                    let live_location_share = LiveLocationShare {
                        user_id: event.sender,
                        last_location: LastLocation {
                            location: event.content.location,
                            ts: event.content.ts,
                        },
                        beacon_info: beacon_info.content,
                    };

                    // Send the live location update to all subscribers.
                    let _ = sender.send(live_location_share);
                }
            }
        });

        let _ = beacon_event_handler_handle;
    });

    (handle, receiver)
}
```
