### ISSUE TITLE
[meta] Latest Event API, the missing one

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#4112]
The Latest Event represents the event that is displayed in the Room List under each room item, or displayed as a Thread Summary. It is important, and must be reactive. It follows several constraints, such as:

- Not all events are a candidate to be a Latest Event, e.g. state events aren't candidate; thus the Latest Event has to paginate through events in reverse order (from newest to oldest) to find a suitable event if any, otherwise the information that no candidate has been found must be present,
- It must represent remote _and_ local events for a better user experience.

The Latest Event API in its current form was added a bit in an ad-hoc way, since we needed the feature but lacked the proper storage layer for events, and the proper send queue. What we can re-use though is all the logic to find a suitable event, which was not trivial to write in an efficient way knowing we have to deal with encrypted event and so on.

Today is different: We have the Event Cache API, and we have the Send Queue API. Those are the two components we need to write a proper Latest Event API! I love it when a plan comes together.

The Latest Event API in its current form is scattered in multiple crates. It's going to be hard to “migrate”, or move things together. The plan we came up with the team is to write a new API from scratch, and then migrate the components using a Latest Event one by one.

> [!IMPORTANT]
>
> ### Storage
>
> A note about the storage. The Event Cache API has its own storage. The Send Queue API has its own storage. The Latest Event API will be _computation only_, no storage is required, and that will solve multiple problems. Right now, the Latest Event is stored in `RoomInfo`, which is not a good place.

> [!IMPORTANT]
>
> ### Thread
>
> Another note about threads. The Latest Event API in its current form is only used by the Rooms. But we need it to work with Threads too, as it is required for Thread Summary.
>
> See https://github.com/matrix-org/matrix-rust-sdk/issues/6013

## Product decisions/questions

- If the latest event is an edit, show it if it edited the previous latest rendered event.
- If the latest event has been redacted, do we show "a message has been redacted", or the previous preview event?
- What counts as an interesting latest preview event?
  - We already have made some decisions there, but what about reactions?
- If there's a local echo that hasn't been sent yet (and it should've been sent, say, 8 hours ago), but there's been new messages in the room since then, what do we show: the local echo or the most up to date message?
- If there's a new in-thread message in a room, can it become the latest preview event for that room, or are only main-thread messages candidates for being the latest preview event?
  - Product proposes that only the main-timeline messages are candidates for the latest preview event for a room.

### Create the Latest Event API

- [x] Create the Latest Event API
  - [x] The entry point is `matrix_sdk::latest_events::LatestEvents`
  - [x] `LatestEvents` is lazy, it computes and keeps only requested `LatestEvent`s in memory
  - [x] `LatestEvents` does not run one task per room or thread; ideally we want one or two tasks to handle all our needs, so that it reduces the pressure on the system
  - [x] Provide a `LatestEvent` type
  - [x] Provide a `LatestEventSubscriber` type
    - [x] It implements `Stream<Item = LatestEvent>`
    - [ ] ❓ It implements an “auto-drop” mechanism: when there is no more listener for all clones of the same `LatestEventSubscriber`, lets' drop it from `LatestEvents`
  - [x] `LatestEvents` listens to the Event Cache for remote events
    - [x] Provide a `LatestEvents::subscribe_to_room(&self, &RoomId) -> (Option<LatestEvent>, LatestEventSubscriber)` (note: `Option<LatestEvent>` to handle the case where there is no suitable `LatestEvent`)
    - [x] Provide a `LatestEvents::subscribe_to_thread(&self, &RoomId, &EventId) -> (Option<LatestEvent>, LatestEventSubscriber)`
    - [x] `LatestEvents` uses the Event Cache to find a suitable event
      - [ ] Be able to back-paginate in the storage
      - [ ] Be able to back-paginate in the network
  - [x] `LatestEvents` listens to the Send Queue for local events
    - [x] Send Queue has a higher priority than Event Cache, i.e. if there is a local event, it must always be used for the `LatestEvent`

### Use the Latest Event API

- [x] Use the Latest Event API
  - [x] `matrix_sdk_ui::room_list_service` uses `LatestEvents`
    - [x] `RoomListService::subscribe_to_rooms` automatically calls `LatestEvents::listen_to_room`
    - [x] `LatestEvents` will store the `LatestEvent` in the `RoomInfo` for caching purposes
    - [x] Saving `LatestEvent` in `RoomInfo` will trigger a `RoomInfoNotableUpdate`, which will trigger an update on `RoomList`, it's free
    - [x] Initialise the `LatestEventValue` with the value loaded in `RoomInfo`
    - [x] Create a new sorter: https://github.com/matrix-org/matrix-rust-sdk/issues/5365
    - [x] `room_list_service::Room::latest_event()` uses `LatestEvents` to retrieve a single `LatestEvent`
      - [x] This method no longer needs a `Timeline` to fetch the `LatestEvent`!

### Clean up

- [x] Clean up
  - [x] Get rid of the code handling re-decryption of the latest preview event, in the matrix-sdk-base crate.
  - [x] Remove the old `LatestEvent` API wherever it lives

### Triaging

Check if the following issues are solved

- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/5317
  - https://github.com/matrix-org/matrix-rust-sdk/pull/6035 
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/5726
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/5983

This meta issue closes:

- Close https://github.com/element-hq/element-x-ios/issues/3166
- Close https://github.com/element-hq/element-x-ios/issues/3698
- Close https://github.com/element-hq/element-x-ios/issues/1775

### See also

- #3872: An encrypted event is decrypted during the sync flow. Sometimes, it's not possible to decrypt an encrypted event because not all information are present. In this case, we need to re-decrypt it later. The re-decryption logic current lives in the `matrix_sdk_ui::timeline`, but it should move inside the Event Cache soon. How it will interact with the Latest Event API is still unclear but ultimately should be transparent (the `RoomEventCache` stream of updates should notify that a new event has been updated, and the machine should handle that seamlessly).

Part of #3058.
Related to: https://github.com/element-hq/element-meta/issues/2944

---

<figure role="presentation">
<p align="center"><img src="https://github.com/user-attachments/assets/51259745-fe72-41b1-8883-255f96882317" width="50%" /></p>
<figcaption><p align="center"><a href="https://it.wikipedia.org/wiki/David_(Bernini)">David (Bernini)</a></p></figcaption>
</figure>

**Comment by mxandreas** [comment]
Regarding product/design questions. As we were tackling this in a slightly more specific context with @americanrefugee (which was to show local echos and the fact if the room has any pending or failed messages), our guiding principle was consistency between the timeline of the room and the room list - whatever is the latest event in the room, should be also shown in the room list. I think for most scenarios this works well+ from user perspective and its additional benefit is that it saves us from potentially long conversations discussing what a good alternative logic is. Or from explaining this to users if they do not follow that logic.

About the specific questions, then:

> If the latest event is an edit, show it if it edited the previous latest rendered event.

Yes (I guess), although I would specify this as: if it edited the last message in the room timeline.

> If the latest event has been redacted, do we show "a message has been redacted", or the previous preview event?

Message has been redacted. If this not helpful, we better offer an option to hide redacted messages at all.

> What counts as an interesting latest preview event?
> We already have made some decisions there, but what about reactions?

I can't any imagine any useful scenario. Showing reactions on the latest message of the timeline, but that is probably also quite far fetched.

> If there's a local echo that hasn't been sent yet (and it should've been sent, say, 8 hours ago), but there's been new messages in the room since then, what do we show: the local echo or the most up to date message?

By the guideline, it is the local echo (as it should be the one that appears at the bottom of the timeline). Additionally, we would also indicate that the room has [pending messages](https://www.figma.com/design/AO7bFhGSUQt4IyBhmW26Cu/Room-List---Navigation--new-?node-id=1085-19869&t=jn1EYmWIFGhyCMqd-4). Also, I do not think it is a very frequent scenario when you have a pending message for several hours but then you get new messages - unless you upload a gigabyte-size video, or?

> If there's a new in-thread message in a room, can it become the latest preview event for that room, or are only main-thread messages candidates for being the latest preview event?

As the point of the Thread is not to "pollute" the main timeline, I think its messages should also not appear in the room list.

**Comment by wrjlewis** [comment]
Hey @mxandreas, I'd like to advocate for emoji reactions to be included as a valid latest event (ie the room list preview), in ElementX ultimately. Are you convinced that reactions should not be included? **(This is obviously your call, just want to double check)**.

The core issue around this is that there is no visibility into reactions unless you actively open each conversation, especially for reactions that carry meaningful context. 


For example:

1) I message someone asking "Can I get approval for holiday on the 7th" and they reply with a reaction "👍" - I won't see it unless I check periodically for a potentially infinite amount of time.

2) Someone replies with "👎" to a comment or proposal I shared - I miss that feedback since there is not an indication of it without opening the room and scrolling back. 


Ideally we'd have reactions in an activity centre (like Slack and Teams), and the room list preview to show reactions as a valid latest event (like WhatsApp and iMessage: John reacted ✅ to "Please complete the weekly report"). 

Since it is minimal effort / free to enable reactions a valid last event, this could at least get us closer to an ideal state?


To play devils advocate, you might not want reactions in the room list previews if you have large company rooms with messages that get tons of reactions, but I'd guess this is a far less frequest occurence/scenario weighed up against how many contextual reactions are flying about unnoticed.

**Comment by wrjlewis** [comment]
Re my previous comment, I note that emoji reactions are displayed as a latest event in Element Web:

<img width="382" height="165" alt="Image" src="https://github.com/user-attachments/assets/a5c76c43-67a8-4d8f-9431-cbd13feab185" />

**Comment by Hywan** [comment]
@wrjlewis Interesting, thanks for testing on EW.

**Comment by jplatte** [comment]
It may be worthwhile to distinguish reactions to one's own messages, and reactions to other people's messages? I'm used to getting notifications for the former from Signal (so I think it would also make sense as latest message), for the latter I don't see any value.

**Comment by Hywan** [comment]
## Thread support

⚠️ Moved to https://github.com/matrix-org/matrix-rust-sdk/issues/6013 ⚠️

**Comment by ganfra** [comment]
So I've been testing the `newLatestEvent` api on EXA, and it's working well.
The only thing that hits me, is having no `profileDetails/sender` for the `LatestEventValue.Local`.
This would be useful to have it too here, so we can properly render local echo of emote for exemple.

**Comment by Hywan** [comment]
@ganfra https://github.com/matrix-org/matrix-rust-sdk/pull/5885/ here we are

**Comment by Hywan** [comment]
Closing as all features have been implemented.

**Comment by manuroe** [comment]
Thanks @Hywan ! For the record, https://github.com/matrix-org/matrix-rust-sdk/issues/5983 will be addressed separately in 2026 Q1.

**Comment by wrjlewis** [comment]
> Closing as all features have been implemented.

@Hywan OOI did we also manage to get emoji reactions to be included as a valid latest event? Like on EW. 

(sorry hit the pin button by mistake there when trying to edit :D )

**Comment by Hywan** [comment]
@wrjlewis Not yet because we need proper automatic backpagination to implement the feature reliably. If we sync with SS and get a single event, if it's a reaction but we don't if it relates to one of our own events, we can't display the reaction, which is rather an inconsistent behaviour.
