### ISSUE TITLE
v0.5.0 Tracking Issue

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#595]
Aside from the [issues in the milestone](https://github.com/matrix-org/matrix-rust-sdk/milestone/2), we have the following to finish so we can release v.0.5.0 to crates.io :

- [x] Decide upon Changelog generation and document and CI-enforce its usage, refs #482
- [x] Feature-gate newly added `timeline`-related-APIs behind `experimental-timeline`-flag (refs #631 )
- [x] Update Readme and Changelog for the release, expand upon supported matrix versions (refs #404 )
- [x] Decide upon the way to communicate the sled-future
- [x] Decide upon whether we bump MSRV to 1.60 to support weak feature dependencies, refs #591 
- [x] Release latest Vodozemac
- [x] Release latest Ruma
